@extends('pages.layout.app2')
@section('content')

    <main id="main"><table class="Subsection-Header-Content-B-Table scroll-active">
            <tbody><tr>
                <td><h1>Nations Star Bank PLC CardControl Mobile App </h1></td>
            </tr></tbody>
        </table><table class="Subsection-Table scroll-active">
            <tbody><tr>
                <td><h3>Debit Card Protection at Your Fingertips</h3><p>Nations Star Bank PLC CardControl is a mobile application that helps you protect your debit card with the push of a button.</p><p>The app allows you to create transaction alerts and gives you the ability to define when, where, and how your debit cards are used.</p><p>Simply download the app on your smartphone to gain quick access to the Nations Star Bank PLC CardControl, then customize your alert preferences and usage settings to monitor and manage your cards. </p><p><img src="ContentImageHandler4689.jpg?ImageId=157905" alt="Card Control Icon" width="177" height="177" border="0" be_marvel="1" onerror="this.onerror=null;this.src='ContentImageHandler4689.jpg?ImageId=157905'"></p>
                    <h2 id="anchor-1">Card Control Functions:</h2><p><strong>Control Preferences</strong></p><p>The Locations control can restrict debit card transactions to merchants located within a certain range of your location (using your phone's GPS); transactions requested outside of the specified range can be declined. The My Region control uses city, state, country, or zip code on an expandable interactive map; transactions requested by merchants outside of a specific region can be declined.</p><p>The Merchant functionality also controls transaction activity based on merchant categories, such as gas stations, department stores, restaurants, entertainment, travel, and groceries, and the Transaction Type section provides management by the type being performed, whether In-Store, eCommerce, Mail/Phone Order or ATM transaction.</p><p>Spend Limits is a single maximum limit per transaction that you can choose to assign on each transaction regardless of its Location, Merchant Type, or Transaction Type and any transaction in excess of this threshold would be denied.</p><p><strong>Alert Preferences</strong></p><p>Though it functions much the same as the Control Preferences above, instead of limiting transactional activity based on your preferences, it only alerts you to transactions based on your predetermined settings. Alerts for debit card activity can be set up to keep you informed of your debit usage and help you quickly detect unauthorized or fraudulent activity. CardControl can send an alert when a card is used, regardless of whether it was declined or approved. Alerts are sent in real-time, immediately after a transaction has taken place. Again, as with Controls, there are four primary Alert types – Location, Merchant, Transaction Type, and Transaction Limit. And you may set an alert for any of the associated locations, merchants, types, and dollar limits.  </p><p><strong>Card On/Off Setting</strong></p><p>This feature is very important in assisting in fraud prevention. It allows you in real-time to turn your card off in the event it has been stolen or you have lost it. When the card is "on," transactions are allowed in accordance with your usage settings. When the card is "off," one-time purchases or withdrawals are denied until the card is subsequently turned back "on." Preauthorized recurring payments may still be completed when the card is “off”. This control can be used to disable a lost or stolen card, prevent fraudulent activity, or control spending. This setting does not remove the customer’s requirement to notify the bank immediately in the event their card is lost or stolen. Delay in the notification, by the customer to the bank, may increase the customer’s financial liability for any fraudulent activity.</p><p><br><strong>Additional Benefits &amp; Capabilities</strong></p><ul>
                        <li>Real-time balance inquiries</li><li>Locating ATMs</li><li>Cardholders can receive alerts to monitor transactions and protect their accounts</li><li>Cardholders can actively manage their money and take charge of their card usage</li><li>Parents can remotely control and monitor their children's spending</li><li>Businesses can ensure spending policy compliance</li></ul>
                    <p>  </p></td>
            </tr></tbody>
        </table>
        </main>
@endsection
