@extends('pages.layout.app2')
@section('content')

    <main id="main"><table class="Subsection-Header-Content-B-Table scroll-active">
            <tbody><tr>
                <td><h1>Diversity &amp; Inclusion</h1></td>
            </tr></tbody>
        </table><table class="Subsection-Table scroll-active">
            <tbody><tr>
                <td><p>We know we’re all richer together and this is why, at Nations Star Bank PLC, diversity is strength and we’re committed to maintaining an inclusive organization.</p><h2 id="anchor-1">Diversity Policy Statement</h2><p>Nations Star Bank PLC is committed to fostering, cultivating and preserving a culture of diversity and inclusion. We are committed to including, integrating and serving individuals who represent different groups as defined by race, ethnicity, gender, sexual orientation, religion, age, disability, socioeconomic and family status, political affiliation, and national origin. This commitment can be seen throughout our bank, from our employees to our community outreach efforts.<br>Our associates bring a diversity of backgrounds, perspectives, and experiences that are reflective of the communities and customers we serve. The unique capabilities and talents that our employees invest in their work represent a significant part of not only our culture but our reputation and achievements as well. We embrace and encourage our employees’ differences and diverseness.</p><p>Prosperity’s diversity practices form a foundation to our policies on recruitment and selection, compensation and benefits, professional development and training, promotions, transfers, and workforce reductions. The bank further administers all contractual relationships in a nondiscriminatory manner.</p><p>At Nations Star Bank PLC, we are focused on supporting the communities we serve and creating a diverse and inclusive environment.</p></td>
            </tr></tbody>
        </table><table class="Subsection-Table scroll-active">
            <tbody><tr>
                <td><h2 id="anchor-2">2021 Diversity and Inclusion Summary</h2><h3>Workforce Diversity</h3><p>As an affirmative action employer, Nations Star Bank PLC is fully committed to the concept and practice of equal opportunity through diversity and inclusion.</p><p>In 2021, our workforce, from senior officers to tellers, was 46% minority and 75% female. Through our commitment to a diverse workforce, we will continue to see positive numbers.</p><ul>
                        <li>We create an inclusive work environment by hiring, training, and retaining associates from diverse backgrounds.</li><li>We encourage associates to recruit new team members through our Referral Reward Program.</li><li>We have reached out to many organizations that assist women and minorities in job services in order to attract a more diverse group of applicants.</li><li>Our Diversity Officer works with associates on understanding the importance of diversity and how to actively develop an inclusive work environment.</li><li>We participate in a variety of activities that reflect the cultural diversity within the communities we serve.</li><li>We strive to select vendors/suppliers who reflect the diversity of the communities we serve.</li><li>Our Marketing team develops strategies to reach multicultural markets.</li></ul>
                    <h3>Supplier Diversity</h3><p>Nations Star Bank PLC is also committed to the practice of diversity and inclusion within its procurement and business practices. We strive to initiate, build and maintain relationships with suppliers who share our commitment to diversity, and we welcome the opportunity to establish long-term partnerships with minority and women-owned businesses.</p><p>We currently have relationships with dozens of vendors on a corporate level and hundreds on a local level. The following statements are from a few of our corporate level vendors who share our commitment to diversity and inclusion:</p><ul>
                        <li>“We are an equal opportunity employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, national origin, disability status, protected veteran status, or any other characteristic protected by law.”</li><li>“We believe that highly engaged, diverse associates are the foundation for building a better company and a better world. We strive to ensure our workplace is inclusive and values each individual and helps associates to reach their full potential.”</li><li>“Our company has made a commitment to diversity that is based on inclusion, understanding, and acceptance. This commitment enables us to help our employees thrive in careers that allow them to reach their full potential, meet and exceed our clients' needs, and provide fair and equal opportunity to our suppliers.”</li><li>“Our equal opportunity employment policy assures that there will be no discrimination or harassment against an employee or applicant on the grounds of race, color, religion, sex, sexual orientation, gender identity, age, disability, national origin, veteran status or any other factor considered unlawful by applicable laws and regulation.”</li><li>“We are an equal opportunity and affirmative action employer. We make employment decisions without regard to race, color, religion, sex, national origin, veteran status, disability status, pregnancy, or any other basis protected by federal, state, or local law. We are committed to diversity in the workplace and strive to support candidates with disabilities.”</li></ul>
                </td></tr>
            </tbody></table>
        <table class="Subsection-Table"><tbody>
            <tr><td>
                    <p>We will continue to evaluate and nurture our relationships with our suppliers to ensure that we remain inclusive and promote diversity in all areas of Nations Star Bank PLC's business practices.</p></td>
            </tr></tbody>
        </table></main>
@endsection
